include:
- ./func/*
kind: ArchiveUploadSpec
name: func-Ao1g

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: update-experience-time-fn-b68a8363-e04a-47dd-b000-c1d7005ed771
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: update-experience-time-env
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://func-Ao1g
status:
  buildstatus: pending
  lastUpdateTimestamp: "2022-07-21T13:25:04Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: update-experience-time-fn
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: newdeploy
      MaxScale: 1
      MinScale: 1
      SpecializationTimeout: 120
      TargetCPUPercent: 80
    StrategyType: execution
  concurrency: 500
  environment:
    name: update-experience-time-env
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: main.update_experience_time
    packageref:
      name: update-experience-time-fn-b68a8363-e04a-47dd-b000-c1d7005ed771
      namespace: default
  requestsPerPod: 10000
  resources: {}
