apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: onb-us-mkt-exp-rt
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: onb-us-mkt-exp-fn
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /onboarding/update_w8_ben
    tls: ""
  method: ""
  methods:
  - PUT
  prefix: ""
  relativeurl: /onboarding/update_experience_time
