apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: update-experience-time-rt
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: update-experience-time-fn
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /update-experience-time
    tls: ""
  method: ""
  methods:
  - PUT
  prefix: ""
  relativeurl: /update-experience-time
